name: unit test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: npm install
      run: npm i
    
    - name: run unit tests
      run: npm run test